spring.application.name=weather-backend

# ── Weather API Configuration (OpenWeatherMap) ──
api.key=da280b1bc9ee36349c63d4fe78c216a3
api.base-url=https://api.openweathermap.org/data/2.5

# ── Server ───
server.port=8080

# ── Logging ─
logging.level.root=INFO
logging.level.com.weather=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
